swagger: "2.0"
info:
  version: "1.0.0"
  title: "swagger definition for com.huaweicloud.cmp.sbf.cloudsdk.iam.IamApi"
basePath: "/v3/auth/tokens"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /:
    get:
      summary: "校验Token的有效性"
      description: "## example:\n  状态码为404时，返回的应答为：\n```\n{\n    \"error\": {\n  \
        \      \"code\": 404,\n        \"message\": \"X-Subject-Token is invalid in\
        \ the request\",\n        \"title\": \"Not Found\"\n    }\n}"
      operationId: "authToken"
      parameters:
      - name: "nocatalog"
        in: "query"
        description: "如果设置该参数，返回的响应体中将不显示catalog信息。任何非空字符串都将解释为true，并使该字段生效。"
        required: false
        type: "string"
      - name: "X-Auth-Token"
        in: "header"
        description: "管理员校验本账号中IAM用户的token的有效性：拥有Security Administrator权限的token。\n\
          \nIAM用户校验自己token的有效性：该IAM用户的token（无需特殊权限）。"
        required: false
        type: "string"
      - name: "X-Subject-Token"
        in: "header"
        description: "待校验的token。"
        required: false
        type: "string"
      responses:
        "200":
          description: "response of 200"
          headers:
            X-Subject-Token:
              type: "string"
          schema:
            $ref: "#/definitions/AuthTokenSuccess"
        "401":
          description: "认证失败"
          headers:
            X-Subject-Token:
              type: "string"
          schema:
            $ref: "#/definitions/AuthTokenFail"
        "403":
          description: "没有操作权限"
          headers:
            X-Subject-Token:
              type: "string"
          schema:
            $ref: "#/definitions/AuthTokenFail"
        "404":
          description: "未找到相应的资源"
          headers:
            X-Subject-Token:
              type: "string"
          schema:
            $ref: "#/definitions/AuthTokenFail"
        "500":
          description: "内部服务错误"
          headers:
            X-Subject-Token:
              type: "string"
          schema:
            $ref: "#/definitions/AuthTokenFail"
    post:
      operationId: "createToken"
      parameters:
      - name: "nocatalog"
        in: "query"
        description: "如果设置该参数，返回的响应体中将不显示catalog信息。任何非空字符串都将解释为true，并使该字段生效。"
        required: false
        type: "string"
      - name: "X-Auth-Token"
        in: "header"
        description: "获取委托Token时需要此参数，表示：被委托方B账号中的IAM用户B具有Agent Operator权限的token"
        required: false
        type: "string"
      - in: "body"
        name: "request"
        required: false
        schema:
          $ref: "#/definitions/CreateTokenRequest"
      responses:
        "200":
          description: "response of 200"
          headers:
            X-Subject-Token:
              type: "string"
definitions:
  AuthTokenFail:
    type: "object"
    properties:
      error:
        $ref: "#/definitions/Error"
  Error:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
      title:
        type: "string"
  AuthTokenSuccess:
    type: "object"
    properties:
      token:
        description: "获取到的token信息"
        $ref: "#/definitions/Token"
  Catalog:
    type: "object"
    properties:
      endpoints:
        type: "array"
        description: "终端节点"
        items:
          $ref: "#/definitions/Endpoint"
      id:
        type: "string"
        description: "服务ID"
      name:
        type: "string"
        description: "服务名称"
      type:
        type: "string"
        description: "该接口所属服务"
  Domain:
    type: "object"
    properties:
      name:
        type: "string"
        description: "IAM用户所属账号名称，获取方式参见：[获取账号、IAM用户、项目、用户组、区域、委托的名称和ID](https://support.huaweicloud.com/intl/zh-cn/api-iam/iam_17_0002.html)"
      id:
        type: "string"
        description: "IAM用户所属账号ID，获取方式参见：[获取账号、IAM用户、项目、用户组、区域、委托的名称和ID](https://support.huaweicloud.com/intl/zh-cn/api-iam/iam_17_0002.html)"
  Endpoint:
    type: "object"
    properties:
      id:
        type: "string"
        description: "终端节点ID"
      region:
        type: "string"
        description: "终端节点所属区域"
      url:
        type: "string"
        description: "终端节点的URL"
      interface:
        type: "string"
        description: "接口类型，描述接口在该终端节点的可见性。值为\"public\"，表示该接口为公开接口。"
      region_id:
        type: "string"
        description: "终端节点所属区域ID"
  Project:
    type: "object"
    properties:
      id:
        type: "string"
        description: "项目ID，获取方式参见：[获取账号、IAM用户、项目、用户组、区域、委托的名称和ID](https://support.huaweicloud.com/intl/zh-cn/api-iam/iam_17_0002.html)"
      name:
        type: "string"
        description: "项目名称，获取方式参见：[获取账号、IAM用户、项目、用户组、区域、委托的名称和ID](https://support.huaweicloud.com/intl/zh-cn/api-iam/iam_17_0002.html)"
      domain:
        description: "项目所属账号信息"
        $ref: "#/definitions/Domain"
  Role:
    type: "object"
    properties:
      id:
        type: "string"
        description: "权限ID。默认显示为0，非真实权限ID"
      name:
        type: "string"
        description: "权限名称"
  Token:
    type: "object"
    properties:
      domain:
        description: "获取token的IAM用户所属的账号信息。如果获取token时请求体中scope参数设置为domain，则返回该字段"
        $ref: "#/definitions/Domain"
      user:
        description: "获取token的IAM用户信息"
        $ref: "#/definitions/User"
      methods:
        type: "array"
        description: "获取token的方式"
        items:
          type: "string"
      project:
        description: "获取token的IAM用户所属账号的项目信息。如果获取token时请求体中scope参数设置为project，则返回该字\
          段"
        $ref: "#/definitions/Project"
      roles:
        type: "array"
        description: "token的权限信息"
        items:
          $ref: "#/definitions/Role"
      catalog:
        type: "array"
        description: "服务目录信息"
        items:
          $ref: "#/definitions/Catalog"
      issued_at:
        type: "string"
        description: "token下发时间"
      expires_at:
        type: "string"
        description: "token过期时间"
  User:
    type: "object"
    properties:
      name:
        type: "string"
        description: "IAM用户名"
      id:
        type: "string"
        description: "IAM用户ID"
      domain:
        description: "IAM用户所属的账号信息"
        $ref: "#/definitions/Domain"
      password_expires_at:
        type: "string"
        description: "密码过期时间（UTC时间），\"\"表示密码不过期"
  AssumeRole:
    type: "object"
    required:
    - "xrole_name"
    properties:
      domain_id:
        type: "string"
        description: "委托方A的账号ID。\"domain_id\"与\"domain_name\"至少填写一个"
      domain_name:
        type: "string"
        description: "委托方A的账号名称。\"domain_id\"与\"domain_name\"至少填写一个"
      xrole_name:
        type: "string"
        description: "委托方A创建的委托的名称"
  Auth:
    type: "object"
    required:
    - "identity"
    - "scope"
    properties:
      identity:
        description: "认证参数"
        $ref: "#/definitions/Identity"
      scope:
        description: "token的使用范围，取值为project或domain，二选一即可\n如果是获取委托Token，则需要填写委托方A的\
          project或domain，填写其中任一即可\n```\n说明：\n使用全局区域的Endpoint调用该接口时，推荐您将scope设置为domain，\
          该token可以跨区域使用，如果将scope设置为project，该token仅能在指定的project中使用，不能跨区域使用。"
        $ref: "#/definitions/Scope"
  BaseProject:
    type: "object"
    properties:
      id:
        type: "string"
        description: "项目ID，获取方式参见：[获取账号、IAM用户、项目、用户组、区域、委托的名称和ID](https://support.huaweicloud.com/intl/zh-cn/api-iam/iam_17_0002.html)"
      name:
        type: "string"
        description: "项目名称，获取方式参见：[获取账号、IAM用户、项目、用户组、区域、委托的名称和ID](https://support.huaweicloud.com/intl/zh-cn/api-iam/iam_17_0002.html)"
  CreateTokenRequest:
    type: "object"
    required:
    - "auth"
    properties:
      auth:
        description: "认证信息"
        $ref: "#/definitions/Auth"
  Identity:
    type: "object"
    required:
    - "assume_role"
    - "methods"
    properties:
      methods:
        type: "array"
        description: "认证方法\n使用密码认证时，必须为[password]\n使用使用密码+虚拟MFA时，必须为[password, totp]\n\
          获取委托Token时，必须为[assume_role]"
        items:
          type: "string"
      password:
        description: "IAM用户密码认证信息\n密码认证、密码+虚拟MFA认证时，必须填写该参数\n```\n说明：\nuser.name和\
          user.domain.name可以在界面控制台“我的凭证”中查看，具体获取方法请参见：[获取账号、IAM用户、项目、用户组、区域、委托的名称和\
          ID](https://support.huaweicloud.com/intl/zh-cn/api-iam/iam_17_0002.html)。\
          \n如果是第三方系统用户，直接使用联邦认证的用户名和密码获取token，系统会提示密码错误。需要在华为云的登录页面，通过“忘记密码” 功能，在华\
          为云中设置登录密码，并在password中输入新设置的密码。\n该接口提供了锁定机制用于防止暴力破解，调用时，请确保用户名密码正确，输错一定次数\
          （[管理员](https://support.huaweicloud.com/intl/zh-cn/usermanual-iam/iam_01_0001.html)可\
          设置该规则，方法请参见：[账号锁定策略](https://support.huaweicloud.com/intl/zh-cn/usermanual-iam/iam_07_0001.html)）\
          将被锁定。"
        $ref: "#/definitions/Password"
      totp:
        description: "totp认证信息，仅在您已开启虚拟MFA方式的登录保护功能时需要填写该参数"
        $ref: "#/definitions/Totp"
      assume_role:
        description: "assume_role的具体信息"
        $ref: "#/definitions/AssumeRole"
  Password:
    type: "object"
  Scope:
    type: "object"
    properties:
      domain:
        description: "委托方A的domain信息。表示获取的token可以跨区域使用，domain支持id和name，填写任一即可"
        $ref: "#/definitions/Domain"
      project:
        description: "委托方A的项目信息，表示获取的token仅能访问指定项目下的资源，project支持id和name，填写任一即可"
        $ref: "#/definitions/BaseProject"
  Totp:
    type: "object"
